// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupeaI.Models;

namespace SupeaI.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SupeaI.Models.Mst_Available", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Del_Flag")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<int>("Spend_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Mst_Available");
                });

            modelBuilder.Entity("SupeaI.Models.Mst_Fixed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Del_Flag")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Fixed_Name")
                        .HasColumnType("text");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Mst_Fixed");
                });

            modelBuilder.Entity("SupeaI.Models.Mst_Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Icon_Name")
                        .HasColumnType("text");

                    b.Property<string>("Income_Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mst_Income");
                });

            modelBuilder.Entity("SupeaI.Models.Mst_Spend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Icon_Name")
                        .HasColumnType("text");

                    b.Property<string>("Spend_Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mst_Spend");
                });

            modelBuilder.Entity("SupeaI.Models.Mst_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Login_Id")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea");

                    b.Property<string>("User_Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Mst_User");
                });

            modelBuilder.Entity("SupeaI.Models.Tra_Income", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Del_Flag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("Income_Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("Linked_Flag")
                        .HasColumnType("boolean");

                    b.Property<long>("Money")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("User_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Tra_Income");
                });

            modelBuilder.Entity("SupeaI.Models.Tra_Spending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Del_Flag")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Linked_Flag")
                        .HasColumnType("boolean");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Purchase_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Spend_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tra_Spending");
                });
#pragma warning restore 612, 618
        }
    }
}
